// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-stxUn8-IaFwuIAsV_eXE_JqaJ2hDWgs',
    appId: '1:125819431860:web:49b15a6e6a2477283e60e1',
    messagingSenderId: '125819431860',
    projectId: 'chat-app-4302d',
    authDomain: 'chat-app-4302d.firebaseapp.com',
    storageBucket: 'chat-app-4302d.firebasestorage.app',
    measurementId: 'G-BTRKYEF7WH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEnY8m51BjWcmL4krrikLIPgn2ZjzKdk0',
    appId: '1:125819431860:android:44c6b46de71199c23e60e1',
    messagingSenderId: '125819431860',
    projectId: 'chat-app-4302d',
    storageBucket: 'chat-app-4302d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNDJxdMZrU4eCtYfgg5pwrYPiRbqWaqKQ',
    appId: '1:125819431860:ios:361d7b10912ef5223e60e1',
    messagingSenderId: '125819431860',
    projectId: 'chat-app-4302d',
    storageBucket: 'chat-app-4302d.firebasestorage.app',
    iosClientId: '125819431860-ich85a2r5gld905f7pj95v4p2sgdrdno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNDJxdMZrU4eCtYfgg5pwrYPiRbqWaqKQ',
    appId: '1:125819431860:ios:361d7b10912ef5223e60e1',
    messagingSenderId: '125819431860',
    projectId: 'chat-app-4302d',
    storageBucket: 'chat-app-4302d.firebasestorage.app',
    iosClientId: '125819431860-ich85a2r5gld905f7pj95v4p2sgdrdno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-stxUn8-IaFwuIAsV_eXE_JqaJ2hDWgs',
    appId: '1:125819431860:web:a75466ca599a6b543e60e1',
    messagingSenderId: '125819431860',
    projectId: 'chat-app-4302d',
    authDomain: 'chat-app-4302d.firebaseapp.com',
    storageBucket: 'chat-app-4302d.firebasestorage.app',
    measurementId: 'G-ZLK45FF9N1',
  );
}
